### PR TITLE
Add shamu manifest

### PR DESCRIPTION
**Pull request by Lyokanthrope**
Hopefully this all works right. I haven't touched it in a while.

### CODE REVIEW

**Comment by lnjX** [comment]
Please rename your branches in your forks to `halium-7.1` (instead of cm-14.1, we're not developing lineageos here!)

---

And please remove the unnecessary revision= attirbutes in the project tags (the defaults are already given in the remote tag).

**Comment by Lyokanthrope** [comment]
Done. I'm not used to sending stuff upstream so sorry for my lack of organization :P

**Comment by lnjX** [comment]
Absolutely no problem. :)

**Comment by Lyokanthrope** [comment]
Oops, I wasn't sure abut the them repo. Thanks for catching that.

**Pull request merged**
