### PR TITLE
Add LeEco Le Max2 (x2) to devices 

### PR DESCRIPTION
**Pull request by maylton**

### CODE REVIEW

**Comment by maylton** [comment]
@vanyasem

**Comment by vanyasem** [comment]
Please indent your XML properly

**Comment by vanyasem** [comment]
Also create a branch on your fork called "halium-7.1" and let it be the one in your manifest

**Comment by vanyasem** [comment]
And don't use unexisting remoted. I highly doubt that maylton remote exists

**Comment by jbruechert** [comment]
You don't need to specify the revision each time, it's already set by the remote.

**Comment by jbruechert** [comment]
Also the indentation is still wrong. Please have a look at another devices manifest and adjust yours.

**Pull request merged**
