### PR TITLE
Add Motorola Moto G5 (cedric)

### PR DESCRIPTION
**Pull request by reivilibre**
I deviated from the instructions/.dependencies file a bit, copying what other Qualcomm devices have used as I ran into some issue.

I don't believe this has caused any problems thus far.

### CODE REVIEW

**Comment by vanyasem** [comment]
Please specify a branch for `android_device_motorola_qcom-common`

**Comment by vanyasem** [comment]
Also remove a newline before `<remote>`. And one newline after (everything is separated by exactly one newline)

**Comment by vanyasem** [comment]
Also could you please explain your issue to me, as I have no idea why using qcom-common is a problem for your device

**Comment by reivilibre** [comment]
Hello there, sure, I can try and explain the issue.

When originally basing my manifest from [this lineage.dependencies](https://github.com/reivilibre/android_device_motorola_cedric/blob/halium-7.1/lineage.dependencies#L7), I ran into this error:
```
oli@bbm-neon:/media/oli/mldata/halium/halium$ ./halium/devices/setup cedric
*****************************************
I: Configuring for device motorola_cedric
*****************************************
fatal: duplicate path device/qcom/common in /media/oli/mldata/halium/halium/.repo/manifest.xml
fatal: duplicate path device/qcom/common in /media/oli/mldata/halium/halium/.repo/manifest.xml
*******************************************
I: Refreshing device vendor repository: device/motorola/cedric
I: Processing proprietary blob file: ./proprietary-files.txt
I: Processing fstab file: ./rootdir/etc/fstab.qcom
I: Procession device vendor common folder: /device/motorola/qcom-common
I: Processing proprietary blob file: ./common-proprietary-files.txt
wc: device-proprietary-files.txt: No such file or directory
grep: device-proprietary-files.txt: No such file or directory
grep: device-proprietary-files.txt: No such file or directory
cat: device-proprietary-files.txt: No such file or directory
cat: device-proprietary-files.txt: No such file or directory
*******************************************
```

For that reason, I looked at the other motorola device manifests, and changed my manifest to use the same `<project path="device/motorola/qcom-common" name="android_device_motorola_qcom-common" remote="los" />` instead of `<project path="device/qcom/common" name="android_device_qcom_common" remote="los" revision="cm-14.1" />`.

This is also why I didn't specify a revision.
```
./motorola_harpia.xml:    <project path="device/motorola/qcom-common" name="android_device_motorola_qcom-common" remote="los" />
./motorola_lux.xml:    <project path="device/motorola/qcom-common" name="android_device_motorola_qcom-common" remote="los" />
./motorola_merlin.xml:    <project path="device/motorola/qcom-common" name="android_device_motorola_qcom-common" remote="los" />
./motorola_osprey.xml:    <project path="device/motorola/qcom-common" name="android_device_motorola_qcom-common" remote="los" />
./motorola_surnia.xml:    <project path="device/motorola/qcom-common" name="android_device_motorola_qcom-common" remote="los" />
```

Also, `los` seems to already define a revision as so:
```
  <remote name="los"
        fetch="https://github.com/LineageOS"
        revision="refs/heads/cm-14.1" />
```

Should I add a revision anyway? (Note: issues with whitespace acknowledged, those will be in the next commit)

**Comment by vanyasem** [comment]
Regarding the revision - you are right, sorry. But then remove the other "revision" from the manifest that is also not needed

**Comment by vanyasem** [comment]
You got your duplicated error because qcom-common is already defined in Halium manifest by default

**Comment by vanyasem** [comment]
Take a look at this commit after that change was introduced https://github.com/Halium/halium-devices/commit/d1fa999d6478e765ca3cf9a45a4b5c5d5e145270

**Comment by vanyasem** [comment]
Please remove `android_device_motorola_qcom-common` and `android_device_qcom_common` from your manifest and try to build Halium again

**Comment by reivilibre** [comment]
In that case, I should maybe consider that `<project path="device/motorola/qcom-common" name="android_device_motorola_qcom-common" remote="los" />` isn't even necessary, **as it isn't in `potter` (Moto G5 Plus) either**. (Edit: ninja'd)

I will give it a build with that removed, before I conclude that it's not necessary.

**Comment by reivilibre** [comment]
I can confirm that it builds with `<project path="device/motorola/qcom-common" name="android_device_motorola_qcom-common" remote="los" />` removed.

**Comment by vanyasem** [comment]
Do you also need `android_packages_resources_devicesettings`?

**Comment by reivilibre** [comment]
@LNJ2 
Hi there, I'm currently not able to do any work until end of June / start of July.

That said, I don't remember running into such an error myself, but when I do start again, I'll be sure to look into/for that and see what I can do about it.

Thanks.

**Comment by vanyasem** [comment]
@LNJ2 see #106, it's the cause of the issue

**Comment by vanyasem** [comment]
The only thing that makes me hesitate before merging the PR is that `devicesettings` thingie

**Pull request merged**
