### PR TITLE
Add Xiaomi A1 (tissot)

### PR DESCRIPTION
**Pull request by Herrie82**
Add Xiaomi A1 (tissot) support.

Unfortunately the device and vendor repos needed quite some work before they were useful. Patches have been sent upstream to tissot-dev, however seems it's not very active, so linking my own repos for now.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by jbruechert** [comment]
Thank you for the pull request! Could you create a halium-7.1 branch on your device repository so you don't have to override the revision, or are the changes not halium specific?

**Comment by Herrie82** [comment]
In general they're not Halium specific except for the kernel defconfig. I've sent them upstream, we'll see what they do. I'll PR the vendor to TheMuppets as well since they only have 15.1 for Tissot.

**Comment by Herrie82** [comment]
@JBBgameich I sent the proprietary ones to TheMuppets with https://github.com/TheMuppets/proprietary_vendor_xiaomi/pull/90

**Comment by enesutku07** [comment]
photo_2020-03-19_00-47-35

**Comment by nromanko** [comment]
Hi, how to get and install it image?

**Comment by juliardi** [comment]
@enesutku07 how do you install it? I wanted to install Ubuntu Touch on my Xiaomi Mi A1 device, but sadly it is not supported yet by UBPort's official installer

**Pull request merged**
