### PR TITLE
suzu: Add manifest for Sony Xperia X

### PR DESCRIPTION
**Pull request by beidl**
This manifest replaces and removes some default repositories:

* Removal of Qualcomm SELinux policies
* ~bionic: Support for loading binaries and libraries from /odm~
* Qualcomm display HAL: Added "(AOSP)" suffix
* ~Qualcomm Dataservices: AOSP build~

### CODE REVIEW

**Comment by jbruechert** [comment]
I'll have a more carful look at your changes later, but would it be possible to pull request your changes to the repositories you forked from Halium instead of replacing the repo with a fork?

**Comment by fredldotme** [comment]
The required Android bionic is still awaiting pull approval.
https://github.com/Halium/android_bionic/pull/5

The HAL driver author suffix "AOSP" is currently required for Mir to load the non-CAF graphics platform.

**Comment by fredldotme** [comment]
We've since switched back to Halium's bionic as the necessary changes have been merged.

**Comment by jbruechert** [comment]
Looks almost fine now, but can you please apply the formatting that is used in the other manifests before merging?

**Comment by jbruechert** [comment]
The remotes are usually written in multiple lines. Just have a look at the other manifests for inspiration :)
Also, please don't include the halium-install script into the device manifest. If you want it to be included, please create a pull request at the main manifest repo. (The script is not device specific)

**Comment by fredldotme** [comment]
Reorganized a little, should be conform now.
I had to add a custom sepolicy repo with sdcard and exfat SELinux policy generation deactivated. The compile time switch wasn't working so I had to
revert the commit which introduced this behaviour.
Nothing special and only necessary as Halium distributions typically don't use Android's vold anyway.

Kind hint that, should those new repos require to be maintained under the Halium umbrella, you can count me in.

**Pull request merged**
