### PR TITLE
Samsung Galaxy Note 4

### PR DESCRIPTION
**Pull request by tyg3rpro**
Samsung Galaxy Note 4 and the variants that I have reported to me as working from people that have tested other variants along with my UBports Recovery fixes that work on Galaxy Note 4

### CODE REVIEW

**Comment by fredldotme** [comment]
Could you please indent the lines similarly to how other device configs do it? Other than that it LGTM.

**Comment by tyg3rpro** [comment]
are they not? weird, they were indented on when I created it, but yeah, I will do that

**Comment by tyg3rpro** [comment]
Just spaced everything in as requested

**Comment by fredldotme** [comment]
Close! We also indent the `<remotes>`.

**Comment by tyg3rpro** [comment]
Hopefully I got it right this time

**Comment by fredldotme** [comment]
I'll merge this and fix indentation in a separate commit.

**Pull request merged**
