### PR TITLE
manifests: add Xiaomi Redmi Note 7 Pro (violet)

### PR DESCRIPTION
**Pull request by mardy**
Change-Id: Ide9a47b44c71869d7569471083ae0af248265a5c

### CODE REVIEW

**Comment by NotKit** [comment]
Please fix the typo in commit title and force push.

**Comment by mardy** [comment]
Oops, done!

**Comment by Vince1171** [comment]
@mardy  Same comment as Notkit. Please fix the typo in commit title and force push. (it's Redmi, not Redme)

**Comment by mardy** [comment]
> @mardy Same comment as Notkit. Please fix the typo in commit title and force push. (it's Redmi, not Redme)

I did it already long ago :-) The typo was left in the MR title, but that's irrelevant.

**Comment by Vince1171** [comment]
> > @mardy Same comment as Notkit. Please fix the typo in commit title and force push. (it's Redmi, not Redme)
> 
> I did it already long ago :-) The typo was left in the MR title, but that's irrelevant.

there is another typo in the commit (Redme => Redmi ) ;-)

**Comment by mardy** [comment]
> there is another typo in the commit (Redme => Redmi ) ;-)

Ouch, how could I miss it :-)
Fixed!

**Pull request merged**
