### PR TITLE
Add OnePlus 3 / 3T (oneplus3)

### PR DESCRIPTION
**Pull request by vanyasem**
Change-Id: I18cef26ea46c02726205db6d3a72ee4ed7f583d8

### CODE REVIEW

**Comment by jbruechert** [comment]
Could you please remove the apks from the device tree (https://github.com/Halium/android_device_oneplus_oneplus3/blob/halium-7.1/proprietary-files-qc.txt), so the vendor repo doesn't need to be manually modified to make it build? Or is this somehow not neccesary for this device?

**Comment by vanyasem** [comment]
sure, i am currently on it

**Comment by vanyasem** [comment]
I was not able to beat `vendor/oneplus/oneplus3/proprietary/etc/thermal-engine.conf:system/etc/thermal-engine.conf` from `oneplus3-vendor.mk`

**Comment by vanyasem** [comment]
It is ready to merge, feel free to do so

**Comment by lnjX** [comment]
Due to latest changes in halium/android some repos aren't needed anymore: https://github.com/Halium/android/commit/c8b4da4e7bc3b08e3972134023556d8e5b87d92b

**Pull request merged**
