### PR TITLE
Add zuk (z2_plus)

### PR DESCRIPTION
**Pull request by S-8506**
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
<project path="device/zuk/z2_plus" name="android_device_zuk_z2_plus" remote="my" revision="cm-14.1" />
<project path="device/zuk/msm8996-common" name="android_device_zuk_msm8996-common" remote="my" revision="cm-14.1" />
<project path="device/qcom/sepolicy" name="android_device_qcom_sepolicy" remote="my2" revision="cm-14.1" />
<project path="vendor/zuk" name="proprietary_vendor_zuk" remote="my" revision="cm-14.1" />
<project path="kernel/zuk/z2_plus" name="android_kernel_zuk_msm8996" remote="my" revision="cm-14.1" />	
<project path="vendor/qcom/opensource/cryptfs_hw" name="android_vendor_qcom_opensource_cryptfs_hw" remote="los" revision="cm-14.1"  />
	<remote name="my"
	fetch="https://github.com/z2-dev"
	revision="cm-14.1" />
	<remote name="my2"
	fetch="https://github.com/S-8506"
	revision="cm-14.1" />
	
</manifest>

### CODE REVIEW

**Comment by lnjX** [comment]
This still generates errors when compiling:

Please fork the device tree and remove the include of the SettingsLib in it. 😃 
```
device/zuk/msm8996-common/doze/Android.mk:33: frameworks/base/packages/SettingsLib/common.mk: No such file or directory
build/core/ninja.mk:166: die Regel für Ziel „/media/lnj/lnjXdata/halium/7.1/out/build-lineage_z2_plus.ninja“ scheiterte
make: *** [/media/lnj/lnjXdata/halium/7.1/out/build-lineage_z2_plus.ninja] Fehler 1
make: Verzeichnis „/media/lnj/lnjXdata/halium/7.1“ wird verlassen

#### make failed to build some targets (1 seconds) ####
```

**Comment by S-8506** [comment]
Retry to build.......

**Comment by lnjX** [comment]
Now I get:

```
ninja: Entering directory `.'
ninja: error: '/media/lnj/lnjXdata/halium/7.1/out/target/product/z2_plus/kernel', needed by '/media/lnj/lnjXdata/halium/7.1/out/target/product/z2_plus/obj/ROOT/hybris-boot_intermediates/hybris-boot.img', missing and no known rule to make it
build/core/ninja.mk:151: die Regel für Ziel „ninja_wrapper“ scheiterte
make: *** [ninja_wrapper] Fehler 1
make: Verzeichnis „/media/lnj/lnjXdata/halium/7.1“ wird verlassen

#### make failed to build some targets (8 seconds) ####
```

**Comment by S-8506** [comment]
I think now it will work.....

**Comment by lnjX** [comment]
Yeah, it works fine, now.

**Comment by lnjX** [comment]
I have no merge access for this repo, only JBB can merge it and he's away for the next hours. Then he'll probably merge it.

**Pull request merged**
