### PR TITLE
Add manifest for Asus Zenfone 2 Laser (Z00ED)

### PR DESCRIPTION
**Pull request by adazem009**

### CODE REVIEW

**Comment by Vince1171** [comment]
Hi
can you regroup all commits under one, named `Asus Zenfone 2 Laser (Z00ED)` and force push plz ?
thx

**Comment by adazem009** [comment]
> Hi
> can you regroup all commits under one, named `Asus Zenfone 2 Laser (Z00ED)` and force push plz ?
> thx

Hi, the manifest is not ready right now as I was changing the repositories while I was troubleshooting the issues. I'll look at the manifest as soon as possible and fix it if it's missing something. By the way, how can I "force push"?

**Comment by Vince1171** [comment]
> > Hi
> > can you regroup all commits under one, named `Asus Zenfone 2 Laser (Z00ED)` and force push plz ?
> > thx
> 
> Hi, the manifest is not ready right now as I was changing the repositories while I was troubleshooting the issues. I'll look at the manifest as soon as possible and fix it if it's missing something. By the way, how can I "force push"?


it'll depends on which git client you use
https://git-scm.com/docs/git-push
https://stackoverflow.com/questions/46866009/is-there-a-force-push-option-in-github-desktop

**Comment by Vince1171** [comment]
Done

**Pull request merged**
